-- ARCHIVO GENERADO por supabase/scripts/generar-plantilla-puc.ts a partir de packages/shared/src/puc.ts.
-- No editar a mano: cambie puc.ts y vuelva a generar.

create table public.plantilla_puc (
  codigo         text primary key check (codigo ~ '^[1-9][0-9]*$'),
  nombre         text not null,
  naturaleza     char(1) not null check (naturaleza in ('D', 'C')),
  exige_tercero  boolean not null default false
);
alter table public.plantilla_puc enable row level security;
create policy plantilla_ver on public.plantilla_puc for select to authenticated using (true);

insert into public.plantilla_puc (codigo, nombre, naturaleza, exige_tercero) values
  ('1', 'ACTIVO', 'D', false),
  ('11', 'Disponible', 'D', false),
  ('1105', 'Caja', 'D', false),
  ('110505', 'Caja general', 'D', false),
  ('110510', 'Cajas menores', 'D', false),
  ('1110', 'Bancos', 'D', false),
  ('111005', 'Bancos nacionales', 'D', false),
  ('1120', 'Cuentas de ahorro', 'D', false),
  ('112005', 'Bancos — cuentas de ahorro', 'D', false),
  ('13', 'Deudores', 'D', false),
  ('1305', 'Clientes', 'D', false),
  ('130505', 'Clientes nacionales', 'D', true),
  ('1330', 'Anticipos y avances', 'D', false),
  ('133005', 'Anticipos a proveedores', 'D', true),
  ('1355', 'Anticipo de impuestos y contribuciones o saldos a favor', 'D', false),
  ('135515', 'Retención en la fuente', 'D', true),
  ('135517', 'Impuesto a las ventas retenido', 'D', true),
  ('135518', 'Impuesto de industria y comercio retenido', 'D', true),
  ('14', 'Inventarios', 'D', false),
  ('1435', 'Mercancías no fabricadas por la empresa', 'D', false),
  ('143505', 'Mercancías no fabricadas por la empresa', 'D', false),
  ('15', 'Propiedades, planta y equipo', 'D', false),
  ('1524', 'Equipo de oficina', 'D', false),
  ('152405', 'Muebles y enseres', 'D', false),
  ('1528', 'Equipo de computación y comunicación', 'D', false),
  ('152805', 'Equipos de procesamiento de datos', 'D', false),
  ('1592', 'Depreciación acumulada', 'C', false),
  ('159215', 'Equipo de oficina', 'C', false),
  ('159220', 'Equipo de computación y comunicación', 'C', false),
  ('2', 'PASIVO', 'C', false),
  ('21', 'Obligaciones financieras', 'C', false),
  ('2105', 'Bancos nacionales', 'C', false),
  ('210505', 'Sobregiros', 'C', true),
  ('22', 'Proveedores', 'C', false),
  ('2205', 'Nacionales', 'C', false),
  ('220505', 'Proveedores nacionales', 'C', true),
  ('23', 'Cuentas por pagar', 'C', false),
  ('2335', 'Costos y gastos por pagar', 'C', false),
  ('233595', 'Otros costos y gastos por pagar', 'C', true),
  ('2365', 'Retención en la fuente', 'C', false),
  ('236515', 'Honorarios', 'C', true),
  ('236525', 'Servicios', 'C', true),
  ('236530', 'Arrendamientos', 'C', true),
  ('236540', 'Compras', 'C', true),
  ('2367', 'Impuesto a las ventas retenido', 'C', false),
  ('236701', 'IVA retenido', 'C', true),
  ('2368', 'Impuesto de industria y comercio retenido', 'C', false),
  ('236801', 'ICA retenido', 'C', true),
  ('24', 'Impuestos, gravámenes y tasas', 'C', false),
  ('2404', 'De renta y complementarios', 'C', false),
  ('240405', 'Vigencia fiscal corriente', 'C', false),
  ('2408', 'Impuesto sobre las ventas por pagar', 'C', false),
  ('240805', 'IVA generado', 'C', false),
  ('240810', 'IVA descontable', 'D', false),
  ('2412', 'De industria y comercio', 'C', false),
  ('241205', 'Vigencia fiscal corriente', 'C', false),
  ('2495', 'Otros', 'C', false),
  ('249505', 'Impuesto nacional al consumo', 'C', false),
  ('25', 'Obligaciones laborales', 'C', false),
  ('2505', 'Salarios por pagar', 'C', false),
  ('250505', 'Salarios por pagar', 'C', true),
  ('2510', 'Cesantías consolidadas', 'C', false),
  ('251010', 'Cesantías consolidadas', 'C', true),
  ('27', 'Diferidos', 'C', false),
  ('2705', 'Ingresos recibidos por anticipado', 'C', false),
  ('270505', 'Ingresos recibidos por anticipado', 'C', true),
  ('28', 'Otros pasivos', 'C', false),
  ('2805', 'Anticipos y avances recibidos', 'C', false),
  ('280505', 'De clientes', 'C', true),
  ('3', 'PATRIMONIO', 'C', false),
  ('31', 'Capital social', 'C', false),
  ('3105', 'Capital suscrito y pagado', 'C', false),
  ('310505', 'Capital autorizado', 'C', false),
  ('36', 'Resultados del ejercicio', 'C', false),
  ('3605', 'Utilidad del ejercicio', 'C', false),
  ('360505', 'Utilidad del ejercicio', 'C', false),
  ('3610', 'Pérdida del ejercicio', 'D', false),
  ('361005', 'Pérdida del ejercicio', 'D', false),
  ('37', 'Resultados de ejercicios anteriores', 'C', false),
  ('3705', 'Utilidades acumuladas', 'C', false),
  ('370505', 'Utilidades acumuladas', 'C', false),
  ('3710', 'Pérdidas acumuladas', 'D', false),
  ('371005', 'Pérdidas acumuladas', 'D', false),
  ('4', 'INGRESOS', 'C', false),
  ('41', 'Operacionales', 'C', false),
  ('4135', 'Comercio al por mayor y al por menor', 'C', false),
  ('413595', 'Venta de otros productos', 'C', false),
  ('4155', 'Actividades inmobiliarias, empresariales y de alquiler', 'C', false),
  ('415595', 'Otras actividades de servicios', 'C', false),
  ('4175', 'Devoluciones en ventas (DB)', 'D', false),
  ('417505', 'Devoluciones en ventas', 'D', false),
  ('42', 'No operacionales', 'C', false),
  ('4210', 'Financieros', 'C', false),
  ('421005', 'Intereses', 'C', false),
  ('5', 'GASTOS', 'D', false),
  ('51', 'Operacionales de administración', 'D', false),
  ('5105', 'Gastos de personal', 'D', false),
  ('510506', 'Sueldos', 'D', false),
  ('5110', 'Honorarios', 'D', false),
  ('511025', 'Asesoría jurídica', 'D', true),
  ('511030', 'Asesoría financiera', 'D', true),
  ('5120', 'Arrendamientos', 'D', false),
  ('512010', 'Construcciones y edificaciones', 'D', true),
  ('5135', 'Servicios', 'D', false),
  ('513525', 'Acueducto y alcantarillado', 'D', false),
  ('513530', 'Energía eléctrica', 'D', false),
  ('513535', 'Teléfono', 'D', false),
  ('5160', 'Depreciaciones', 'D', false),
  ('516015', 'Equipo de oficina', 'D', false),
  ('516020', 'Equipo de computación y comunicación', 'D', false),
  ('5195', 'Diversos', 'D', false),
  ('519530', 'Útiles, papelería y fotocopias', 'D', false),
  ('519595', 'Otros', 'D', false),
  ('53', 'No operacionales', 'D', false),
  ('5305', 'Financieros', 'D', false),
  ('530505', 'Gastos bancarios', 'D', false),
  ('530520', 'Intereses', 'D', false),
  ('54', 'Impuesto de renta y complementarios', 'D', false),
  ('5405', 'Impuesto de renta y complementarios', 'D', false),
  ('540505', 'Impuesto de renta y complementarios', 'D', false),
  ('6', 'COSTOS DE VENTAS', 'D', false),
  ('61', 'Costo de ventas y de prestación de servicios', 'D', false),
  ('6135', 'Comercio al por mayor y al por menor', 'D', false),
  ('613595', 'Venta de otros productos', 'D', false);
